<?php

/**
 * @file
 * Primary module hooks for validator module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
/**
 * Implements hook_theme().
 */
function validator_theme($existing, $type, $theme, $path) {
  return [
    'validator_form'=>[
      'render element'=> 'form',
      'file' => 'validator.theme.inc',
      ],
    'table_validator'=>[
      'render element'=> 'form',
      'file' => 'validator.theme.inc',
    ]
  ];
}
